
version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      - MSSQL_SA_PASSWORD=130720Palmex;
      - ACCEPT_EULA=Y
      - MSSQL_AGENT_ENABLED=true
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./backups:/var/opt/mssql/backups